### ISSUE TITLE
checkbox hook is too small and can not use the param of flatten when use pdftk tool

### ISSUE THREAD

**Issue by jay763190097** [eemeli/pdf-form-fill#2]
i edit template.pdf  and add some chekboxs and texts in it , set checkbox font size 16.
first: 
```
>pdftk template.pdf fill_form temp.xfdf output result.pdf flatten
```
 Chinese can not be show.English also can not be show.
second:
```
>pdftk template.pdf fill_form temp.xfdf output result.pdf need_apperances
```
Chinese can be show,but it can be edit and the hook is too small
so i give up pdftk....

**Comment by eemeli** [comment]
Could you clarify a bit what seems to be the issue or issues here? I don't understand what you mean by "checkbox hook is too small", and it's not clear how the flatten parameter isn't working for you.

**Comment by jay763190097** [comment]
@eemeli i update my issue on top.

**Comment by jay763190097** [comment]
code:
```
const fs = require('fs');
const { fields, fill } = require('pdf-form-fill');

const srcPdf = './template.pdf';
const tgtPdf = './result.pdf';
const field = { name: 'Value 1', Check2: 'Yes' };

fields(srcPdf)
  .then(shape => console.log(shape))
  .catch(err => console.error(err));

const output = fs.createWriteStream(tgtPdf);
fill(srcPdf, field, {flatten:true})
  .then(stream => stream.pipe(output))
  .catch(err => console.error(err));
```
template.pdf:

![image](https://raw.githubusercontent.com/jay763190097/fill-pdf-utf8/itext-jar/QQ20170609112939.png)

result.pdf:

![image](https://raw.githubusercontent.com/jay763190097/fill-pdf-utf8/itext-jar/QQ20170609113112.png)

**Comment by eemeli** [comment]
It sounds like the issues you're facing are with pdftk, rather than this node.js wrapper for it. I'm closing this issue, and would suggest that you ask for help e.g. on [StackOverflow](https://stackoverflow.com/questions/tagged/pdftk).
