### ISSUE TITLE
Need Help Running on a Mac using JavaScript for Automation (JXA)

### ISSUE THREAD

**Issue by JMichaelTX** [eemeli/pdf-form-fill#3]
Hi,

Your pdf-form-fill tool looks like exactly what I need.  However, I don't know how to run it.
I'm NOT using a web server, but need to run it in a JXA script.  However, the script can run a shell script if need be.

Can you please provide some guidance?  I am very much a npm and shell script novice, so the more detail the better.  Make no assumptions about my knowledge.

Thanks.

**Comment by eemeli** [comment]
Sorry, I've no experience with JXA scripting, and it sounds like your question is rather outside the scope of pdf-form-fill itself.
